### ISSUE TITLE
The purpose of Meta Web Pro fonts

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#27]
There are some font files `fonts/MetaWebPro-Normal.woff` and `fonts/MetaWebPro-Thin.woff`. They have been added by @ronaldtse in the 5e74524295d78e6e4dae62e2e87536ec0180347e (initial commit), and they are also present in the repository which is now named ISO-TC211/isotc211.geolexica.org (both this and that repo derive from the same codebase), but I doubt they have ever been in use. Some forgotten leftover, perhaps? Should I delete them?

cc @strogonoff, maybe you recognize them?

**Comment by ronaldtse** [comment]
I think those were from @strogonoff , let's remove them if they're not used?

**Comment by strogonoff** [comment]
Haha I want to say they were not added by me either, perhaps I’m forgetting something. Either way if there aren’t any references to them they should be safe to remove.

**Comment by ronaldtse** [comment]
Then let's remove them, thanks!

**Comment by skalee** [comment]
They are replicated in all repos.

### TODO

- [ ] Delete from TC211
- [ ] Delete from OSGeo
- [ ] Delete from IEV
- [ ] Delete from Jekyll-Geolexica

**Comment by skalee** [comment]
Unnecessary fonts have been removed from this repository and from all sites.
