### ISSUE TITLE
Staging sites should not be crawled by search engines

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#81]
@ronaldtse Am I right about that?

I guess proper `robots.txt` will do…

### TODO

- [x] Define custom `robots.txt` (#96)
- [x] Update deploy script for TC211 site
- [x] Update deploy script for OSGeo site
- [x] Update deploy script for IEV site

**Comment by ronaldtse** [comment]
Yup!

**Comment by skalee** [comment]
Since merging #96, all sites built with `JEKYLL_ENV` other than `production` will have a disallowing `robots.txt`.
