### ISSUE TITLE
Let's move site source to subdirectory

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#83]
By default, Jekyll takes source files from project's root. Given the fact we have plenty of configuration files, we manage a pretty long exclusion list like [this one](https://github.com/geolexica/isotc211.geolexica.org/blob/745172e4bddf3240736d385c535e0252d9c11190/_config.yml#L164-L191) from TC211 Geolexica, which specifies files that should not be present in generated site. Maintaining this list is a cumbersome and error-prone task.

How about moving the source files to some subdirectory, e.g. `_source`? Jekyll allows for that, it can be changed with just one configuration variable. This eliminates need for that exclusion list entirely, and improves code organization in general.

Since I'm going to apply this change to all sites, I want to consult it first. @ronaldtse @strogonoff what do you think? Any objections?

**Comment by ronaldtse** [comment]
I agree with this change, it’s something we were lazy to do initially since the focus was to get things going fast. Thanks!

**Comment by skalee** [comment]
**TODO**

- [ ] Do it on TC211 Geolexica.
- [ ] Do it on OSGeo Geolexica.
- [ ] Do it on IEV.
- [ ] Do it in Jekyll-Geolexica plugin.

**Comment by skalee** [comment]
A portion of this issue has been extracted to #87. The rest is done, so I'm closing the issue.
