### ISSUE TITLE
Update for Jekyll 4.1

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#94]
A new version has been released recently. Need to go through [changelog](https://jekyllrb.com/docs/history/#v4-1-0) and create few issues for possible improvements or required changes, then update Geolexica gems and sites.

### TODO

- [x] Make Jekyll-Geolexica compatible with Jekyll 4.1 (#117)
- [x] Release a new version of Geolexica-Site gem which uses Jekyll 4.1
- [x] Deploy TC 211 site (https://github.com/geolexica/isotc211.geolexica.org/pull/146)
- [x] Deploy OSGeo site (https://github.com/geolexica/osgeo.geolexica.org/pull/26)
- [x] Deploy IEV site (https://github.com/glossarist/iev-demo-site/pull/56)
